### PR TITLE
Icon replacement from photo to signature

### PR DESCRIPTION
**Pull request by ardacebi**

### CODE REVIEW

**Review by XEngine — APPROVED** [review]

**Comment by ardacebi** [comment]
@XEngine When will you push an update so this can go live?

**Comment by XEngine** [comment]
You can use

```
composer require xengine/flarum-ext-signature:"dev-master"
```

To grab the latest commit

**Comment by ardacebi** [comment]
screenshot_2018-07-18 settings - appybuilder community


It remained the same for some reason.

**Comment by XEngine** [comment]
try to clear flarum's cache

**Pull request merged**
